# Generated by Django 2.1.1 on 2019-10-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='role',
            field=models.CharField(choices=[(1, 'SUPERADMIN'), (2, 'STOREADMIN'), (3, 'GUEST')], default=3, max_length=255),
        ),
    ]
