# Generated by Django 2.1.1 on 2019-10-15 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mainuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime)),
                ('size', models.IntegerField()),
                ('type', models.CharField(choices=[(2, 'CLOTHES'), (4, 'STOREADMIN'), (3, 'TOYS'), (1, 'ALL')], default=1, max_length=255)),
                ('existence', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime)),
                ('service_type', models.CharField(choices=[(2, 'CLEANING'), (3, 'CARSHARING'), (4, 'CARTERING'), (1, 'ALL')], default=1, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
