USER_ADMIN = 1
USER_STOREADMIN = 2
USER_GUEST = 3

USER_ROLES = (
    (USER_SUPERADMIN, 'SUPERADMIN'),
    (USER_STOREADMIN, 'STOREADMIN'),
    (USER_GUEST, 'GUEST'),
)

PRODUCT_ALL = 1
PRODUCT_CLOTHES = 2
PRODUCT_TOYS = 3
PRODUCT_MEAL = 4

PRODUCT_TYPES = (
    (PRODUCT_CLOTHES, 'CLOTHES'),
    (PRODUCT_MEAL, 'MEAL'),
    (PRODUCT_TOYS, 'TOYS'),
    (PRODUCT_ALL, 'ALL'),
)

SERVICE_ALL = 8
SERVICE_CLEANING = 9
SERVICE_CARSHARING = 10
SERVICE_CARTERING = 11

SERVICE_TYPES = (
    (SERVICE_CLEANING, 'CLEANING'),
    (SERVICE_CARSHARING, 'CARSHARING'),
    (SERVICE_CARTERING, 'CARTERING'),
    (SERVICE_ALL, 'ALL'),
)