USER_ADMIN = 1
USER_GUEST = 2

USER_ROLES = (
    (USER_ADMIN, 'ADMIN'),
    (USER_GUEST, 'GUEST'),
)

COLOR_BLACK = 1
COLOR_WHITE = 2
COLOR_RED = 3

COLORS = (
    (COLOR_BLACK, 'BLACK'),
    (COLOR_WHITE, 'WHITE'),
    (COLOR_RED, 'RED'),
)