# Generated by Django 2.1.1 on 2019-10-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task_description',
        ),
    ]
