# Generated by Django 2.1.1 on 2019-11-20 07:14

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191002_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskdocument',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='taskdocument',
            name='task',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=utils.upload.task_document_path, validators=[utils.validators.validate_file_size, utils.validators.validate_extension]),
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
        migrations.DeleteModel(
            name='TaskDocument',
        ),
    ]
